### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by gabrielwolf** [justengel/django_materialize_nav#1]
`pip install django-materialize-nav` gives this error:
```
Collecting django-materialize-nav
  Downloading https://files.pythonhosted.org/packages/a9/87/a899cf40ae16a9aae8c96e6921969798baf0bc0fc63f6a85bfbaf534cea7/django_materialize_nav-0.2.1.tar.gz (1.1MB)
    100% |████████████████████████████████| 1.1MB 6.4MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/nx/swm52jq90fzcdgv3xdcnw9q00000gn/T/pip-install-lctr4ttv/django-materialize-nav/setup.py", line 15, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/nx/swm52jq90fzcdgv3xdcnw9q00000gn/T/pip-install-lctr4ttv/django-materialize-nav/
```
 I use pip 18.0 and python 3.6.5

Any hints?

**Comment by justengel** [comment]
Yeah, in the newer versions of pip they moved the requirements library.
Sorry that's one of the libraries I haven't updated. You can downgrade your
version of pip to something before version 10 (I think).

Also that library might need some work. I'll work on it next week. I'm
hoping to have time tomorrow to fix the install issue.

Pardon my brevity, sent from my phone.

**Comment by justengel** [comment]
Updated. It should work now.

Pardon my brevity sent from my phone.
